# Generated by Django 4.0.6 on 2023-02-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_default_time',
            field=models.DurationField(default='1:00:00'),
        ),
    ]
