# Generated by Django 4.0.6 on 2023-02-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_event_event_default_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('day_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventOnDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_for_event', to='planner.day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_on_day', to='planner.event')),
            ],
        ),
    ]
