# Generated by Django 4.0.6 on 2023-02-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_day_eventonday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventonday',
            name='duration',
            field=models.DurationField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_on_day', to='planner.event')),
        ),
    ]
