# Generated by Django 4.0.6 on 2023-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_eventonday_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventonday',
            name='duration',
            field=models.DurationField(),
        ),
    ]
