# Generated by Django 4.0.6 on 2023-02-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_eventonday_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventonday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.day'),
        ),
    ]
